### ISSUE TITLE
go interview 27 题，在 1.15 上已经编译不过了

### ISSUE THREAD

**Issue by imzhongqi** [pibigstar/go-demo#23]
```go
func Test27(t *testing.T) {
	i := 65
	fmt.Println(string(i))
}
```

conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)

**Comment by pibigstar** [comment]
刚试了下，确实无法编译执行了，多谢指正

**Comment by imzhongqi** [comment]
int32类型的话还是可以转换的
